<a href="https://colab.research.google.com/github/Bilalkhan-cel/Data-Analytics-Using-python/blob/main/second.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Intoduction to NUMPY***


In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
print(arr*2)

[ 2  4  6  8 10]


In [11]:
arr_twoD=np.array([[1,2,3,4],
                [5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [8]:
print(arr_twoD.ndim) # use to find the dimensions of the array either 1D 2D 3D etc

2


In [9]:
print(arr_twoD)

[[ 1  2  3  4]
 [12 12 43  1]]


In [12]:
print(arr_twoD.shape)

(4, 4)


In [13]:
# array slicing arr[start:end:step]

In [24]:
arr_twoD[::-2]

array([[13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [27]:
print(arr_twoD.sum())
print(arr_twoD.mean())
print(arr_twoD.max())
print(arr_twoD.min())
print(arr_twoD.var())
print(arr_twoD.std())

136
8.5
16
1
21.25
4.6097722286464435
